export const DropDownCoursesData = [
    {
      value: "0",
      name: "UG Courses",
      url: "/viewallpage",
      elid: "2",
      subCourses: [
        {
          value: "0",
          name: "Online BBA",
          extraEdgeCourseId: "8",
          clid: "5",
          mlid: null,
          specialization: [
            {
              value: "1",
              name: "BBA General",
              extraEdgeSpecializationId: "20",
              mlid: "2500",
              url: "/ug-courses/online-bba/bba-general",
              uids:["46","72","161","210","221","237","254","272","284","299","339","370","387","430","462","469","496","635",""],
            },
            {
              value: "2",
              name: "Engineering and Project Management",
              extraEdgeSpecializationId: "29",
              mlid: "2509",
              url: "/ug-courses/online-bba/engineering-and-project-management",
              uids:["124",""],
            },
            // {
            //   value: "3",
            //   name: "Strategy and Leadership",
            //   extraEdgeSpecializationId: "30",
            //   mlid: "2510",
            //   url: "/ug-courses/online-bba/strategy-and-leadership",
            //   uids:[""],
            // },
            // {
            //   value: "4",
            //   name: "Travel and Tourism Management",
            //   extraEdgeSpecializationId: "31",
            //   mlid: "2511",
            //   url: "/ug-courses/online-bba/travel-and-tourism-management",
            //   uids:[""],
            // },
            // {
            //   value: "5",
            //   name: "Logistics",
            //   extraEdgeSpecializationId: "33",
            //   mlid: "2513",
            //   url: "/ug-courses/online-bba/logistics",
            //   uids:[""],
            // },
            {
              value: "6",
              name: "Bussiness analyst",
              extraEdgeSpecializationId: "26",
              mlid: "2506",
              url: "/ug-courses/online-bba/buisness-analytics",
              uids:["29","357",""],
            },
            {
              value: "7",
              name: "Retail and Sales Management",
              extraEdgeSpecializationId: "35",
              mlid: "2515",
              url: "/ug-courses/online-bba/retail-and-sales-management",
              uids:[""],
            },
            {
              value: "8",
              name: "International Business Management",
              mlid: "2516",
              extraEdgeSpecializationId: "36",
              url: "/ug-courses/online-bba/international-business-management",
              uids:["26",""],
            },
            // {
            //   value: "9",
            //   name: "International Marketing",
            //   mlid: "2517",
            //   extraEdgeSpecializationId: "37",
            //   url: "/ug-courses/online-bba/international-marketing",
            //   uids:[""],
            // },
            // {
            //   value: "10",
            //   name: "IT and Systems Management",
            //   extraEdgeSpecializationId: "38",
            //   mlid: "2518",
            //   url: "/ug-courses/online-bba/it-and-systems-management",
            //   uids:[""],
            // },
            // {
            //   value: "11",
            //   name: "Finance and Leadership",
            //   extraEdgeSpecializationId: "39",
            //   mlid: "2519",
            //   url: "/ug-courses/online-bba/finance-and-leadership",
            //   uids:[""],
            // },
            {
              value: "12",
              name: "International Finance",
              extraEdgeSpecializationId: "40",
              mlid: "2520",
              url: "/ug-courses/online-bba/international-finance",
              uids:[""],
            },
             {
              value: "13",
              name: "HRM",
              extraEdgeSpecializationId: "25",
              mlid: "2505",
              url: "/ug-courses/online-bba/hrm",
              uids:["25","119","179","195","485","605",""],
            },
             {
              value: "14",
              name: "Finance",
              extraEdgeSpecializationId: "23",
              mlid: "2503",
              url: "/ug-courses/online-bba/finance",
              uids:["120","178","197","484",""],
            }, 
            {
              value: "15",
              name: "Marketing",
              extraEdgeSpecializationId: "22",
              mlid: "2502",
              url: "/ug-courses/online-bba/marketing",
              uids:["28","121","180","196","483","606"],
            },
            {
              value: "16",
              name: "Banking Finance",
              extraEdgeSpecializationId: "21",
              mlid: "2501",
              url: "/ug-courses/online-bba/banking-and-finance",
              uids:["431"],
            },
  
            {
              value: "17",
              name: "Digital Marketing",
              extraEdgeSpecializationId: "24",
              mlid: "2504",
              url: "/ug-courses/online-bba/digital-marketing",
              uids:["122","300","353","403","433","610",""],
            },
  
            {
              value: "18",
              name: "Data Science and Analytics",
              extraEdgeSpecializationId: "28",
              mlid: "2508",
              url: "/ug-courses/online-bba/data-science-and-analytics",
              uids:["123",""],
            },
  
            {
              value: "19",
              name: "Multimedia Management",
              extraEdgeSpecializationId: "32",
              mlid: "2512",
              url: "/ug-courses/online-bba/multimedia-management",
              uids:[""],
            },
  
            // {
            //   value: "20",
            //   name: "Advertising and Branding",
            //   extraEdgeSpecializationId: "34",
            //   mlid: "2514",
            //   url: "/ug-courses/online-bba/advertising-and-branding",
            //   uids:[""],
            // },
  
            // {
            //   value: "21",
            //   name: "Advertisement and Marketing",
            //   extraEdgeSpecializationId: "27",
            //   mlid: "2507",
            //   url: "/ug-courses/online-bba/advertisement-marketing",
            //   uids:[""],
            // },

            {
              value: "22",
              name: "Banking Finance & Insurance Services",
              extraEdgeSpecializationId: "27",
              mlid: "2530",
              url: "/ug-courses/online-bba/banking-finance-insurance-services",
              uids:["354",""],
            },
            {
              value: "23",
              name: "Banking Insurance",
              extraEdgeSpecializationId: "27",
              mlid: "2531",
              url: "/ug-courses/online-bba/banking-insurance",
              uids:["198",""],
            },
            {
              value: "24",
              name: "Business Intelligence & Analytics",
              extraEdgeSpecializationId: "27",
              mlid: "2532",
              url: "/ug-courses/online-bba/business-intelligence-analytics",
              uids:["432",""],
            },
            {
              value: "25",
              name: "Data Analytics",
              extraEdgeSpecializationId: "27",
              mlid: "2533",
              url: "/ug-courses/online-bba/data-analytics",
              uids:["47","609","639",""],
            },
            {
              value: "26",
              name: "Entrepreneurship",
              extraEdgeSpecializationId: "27",
              mlid: "2534",
              url: "/ug-courses/online-bba/entrepreneurship",
              uids:["27","356","608",""],
            },
            {
              value: "27",
              name: "Human Capital Management",
              extraEdgeSpecializationId: "27",
              mlid: "2535",
              url: "/ug-courses/online-bba/human-capital-management",
              uids:["355"],
            },
            {
              value: "28",
              name: "Operation Management",
              extraEdgeSpecializationId: "27",
              mlid: "2536",
              url: "/ug-courses/online-bba/operation-management",
              uids:["177",""],
            },
          ],
          redirectUrl: "/viewallpage/bba"
        },
        {
          value: "1",
          name: "Online B.Com",
          clid: "2",
          extraEdgeCourseId: "10",
          mlid: null,
          redirectUrl: "/viewallpage/bcom",
  
          specialization: [
            {
              value: "1",
              name: "B.Com General",
              extraEdgeSpecializationId: "46",
              mlid: "2200",
              url: "/ug-courses/online-bcom/bcom-general",
              uids:["200","255","265","285","372","390","436","471","615",""],
            },
            {
              value: "2",
              name: "Accouting and Finance",
              extraEdgeSpecializationId: "47",
              mlid: "2201",
              url: "/ug-courses/online-bcom/accounts-and-finance",
              uids:["125",""],
            },
            {
              value: "3",
              name: "International Finance",
              extraEdgeSpecializationId: "57",
              mlid: "2211",
              url: "/ug-courses/online-bcom/international-finance",
              uids:[""],
            },
            {
              value: "4",
              name: "Professional Accounting and Finance",
              extraEdgeSpecializationId: "56",
              mlid: "2210",
              url: "/ug-courses/online-bcom/professional-and-accounting-finance",
              uids:[""],
            },
            {
              value: "5",
              name: "Banking Finance",
              extraEdgeSpecializationId: "48",
              mlid: "2202",
              url: "/ug-courses/online-bcom/banking-finance",
              uids:[""],
            },
            {
              value: "6",
              name: "FinTech",
              extraEdgeSpecializationId: "59",
              mlid: "2213",
              url: "/ug-courses/online-bcom/fin-tech",
              uids:[""],
            },
            // {
            //   value: "7",
            //   name: "Hindi",
            //   extraEdgeSpecializationId: "58",
            //   mlid: "2212",
            //   url: "/ug-courses/online-bcom/hindi",
            //   uids:[""],
            // },{
            //   value: "8",
            //   name: "Auditing",
            //   extraEdgeSpecializationId: "49",
            //   mlid: "2203",
            //   url: "/ug-courses/online-bcom/auditing",
            //   uids:[""],
            // },
            // {
            //   value: "9",
            //   name: "Stock Market Operations",
            //   extraEdgeSpecializationId: "50",
            //   mlid: "2204",
            //   url: "/ug-courses/online-bcom/stock-market-operation",
            //   uids:[""],
            // },
            // {
            //   value: "10",
            //   name: "Law",
            //   extraEdgeSpecializationId: "51",
            //   mlid: "2205",
            //   url: "/ug-courses/online-bcom/law",
            //   uids:[""],
            // },
            // {
            //   value: "11",
            //   name: "International Business",
            //   extraEdgeSpecializationId: "53",
            //   mlid: "2207",
            //   url: "/ug-courses/online-bcom/international-business",
            //   uids:[""],
            // },
            {
              value: "12",
              name: "Behavioural Finance",
              extraEdgeSpecializationId: "54",
              mlid: "2208",
              url: "/ug-courses/online-bcom/behavioural-finance",
              uids:[""],
            },
            {
              value: "13",
              name: "Banking and Insurance",
              extraEdgeSpecializationId: "55",
              mlid: "2209",
              url: "/ug-courses/online-bcom/banking-insurance",
              uids:[""],
            },

            {
              value: "14",
              name: "Banking",
              extraEdgeSpecializationId: "55",
              mlid: "2220",
              url: "/ug-courses/online-bcom/banking",
              uids:["361",""],
            },
            {
              value: "15",
              name: "Corporate Accounting",
              extraEdgeSpecializationId: "55",
              mlid: "2221",
              url: "/ug-courses/online-bcom/corporate-accounting",
              uids:[""],
            },
            {
              value: "16",
              name: "Finance",
              extraEdgeSpecializationId: "55",
              mlid: "2222",
              url: "/ug-courses/online-bcom/finance",
              uids:["360",""],
            },
            {
              value: "17",
              name: "HR Management",
              extraEdgeSpecializationId: "55",
              mlid: "2223",
              url: "/ug-courses/online-bcom/hr-management",
              uids:["362",""],
            },
            {
              value: "18",
              name: "International Finance & Accounting",
              extraEdgeSpecializationId: "55",
              mlid: "2224",
              url: "/ug-courses/online-bcom/international-finance-accounting",
              uids:["50","127","166",""],
            },
            {
              value: "19",
              name: "Marketing",
              extraEdgeSpecializationId: "55",
              mlid: "2225",
              url: "/ug-courses/online-bcom/marketing",
              uids:["369",""],
            },
            {
              value: "20",
              name: "Taxation & Finance",
              extraEdgeSpecializationId: "55",
              mlid: "2226",
              url: "/ug-courses/online-bcom/taxation-finance",
              uids:["165",""],
            },
           
  
          ],
        },
        {
          value: "2",
          name: "Online BA",
          clid: "3",
          mlid: null,
          extraEdgeCourseId: "9",
          redirectUrl: "/viewallpage/ba",
  
          specialization: [
            {
              value: "1",
              name: "BA General",
              extraEdgeSpecializationId: "41",
              mlid: "2300",
              url: "/ug-courses/online-ba/ba-general",
              uids:["149","223","286",""],
            },
            {
              value: "2",
              name: "Journalism and Mass Communication",
              extraEdgeSpecializationId: "42",
              mlid: "2301",
              url: "/ug-courses/online-ba/journalism-and-mass-communication",
              uids:["31","55","242",""],
            },
            {
              value: "3",
              name: "Hindi",
              extraEdgeSpecializationId: "43",
              mlid: "2302",
              url: "/ug-courses/online-ba/hindi",
              uids:["56",""],
            },
            {
              value: "4",
              name: "Economics",
              extraEdgeSpecializationId: "44",
              mlid: "2304",
              url: "/ug-courses/online-ba/economics",
              uids:["54","263","309","434",""],
            },
            {
              value: "5",
              name: "Tourism Administrator",
              extraEdgeSpecializationId: "45",
              mlid: "2305",
              url: "/ug-courses/online-ba/tourism-administrator",
              uids:[""],
            },

            {
              value: "6",
              name: "English",
              extraEdgeSpecializationId: "45",
              mlid: "2314",
              url: "/ug-courses/online-ba/english",
              uids:["51","80","273","310","435",""],
            },
            {
              value: "7",
              name: "History",
              extraEdgeSpecializationId: "45",
              mlid: "2315",
              url: "/ug-courses/online-ba/history",
              uids:["262","311",""],
            },
            {
              value: "8",
              name: "Political Science",
              extraEdgeSpecializationId: "45",
              mlid: "2316",
              url: "/ug-courses/online-ba/political-science",
              uids:["53","82","315","338",""],
            },
            {
              value: "9",
              name: "Politics",
              extraEdgeSpecializationId: "45",
              mlid: "2317",
              url: "/ug-courses/online-ba/politics",
              uids:["264",""],
            },
            {
              value: "10",
              name: "Psychology",
              extraEdgeSpecializationId: "45",
              mlid: "2318",
              url: "/ug-courses/online-ba/psychology",
              uids:["316",""],
            },
            {
              value: "11",
              name: "Public Policy & Development",
              extraEdgeSpecializationId: "45",
              mlid: "2319",
              url: "/ug-courses/online-ba/public-policy-development",
              uids:["313",""],
            },
            {
              value: "12",
              name: "Sociology",
              extraEdgeSpecializationId: "45",
              mlid: "2320",
              url: "/ug-courses/online-ba/sociology",
              uids:["52","81",""],
            },
          ],
        },
        {
          value: "3",
          name: "Online BCA",
          clid: "6",
          mlid: null,
          extraEdgeCourseId: "7",
          redirectUrl: "/viewallpage/bca",
          specialization: [
            {
              value: "1",
              name: "BCA General",
              extraEdgeSpecializationId: "12",
              mlid: "2600",
              url: "/ug-courses/online-bca/bca-general",
              uids:["30","73","148","182","199","222","303","340","371","388","463","470","497",""],
            },
            {
              value: "2",
              name: "Database Management System",
              extraEdgeSpecializationId: "13",
              mlid: "2601",
              url: "/ug-courses/online-bca/data-base-management-system",
              uids:[""],
            },
            {
              value: "3",
              name: "Data Science and Big Data Analytics",
              extraEdgeSpecializationId: "14",
              mlid: "2602",
              url: "/ug-courses/online-bca/data-science-and-big-data-analytics",
              uids:["438",""],
            },
            {
              value: "4",
              name: "Multimedia and Animation",
              extraEdgeSpecializationId: "15",
              mlid: "2603",
              url: "/ug-courses/online-bca/multimedia-and-animation",
              uids:[""],
            },
            {
              value: "5",
              name: "Data Analytics",
              extraEdgeSpecializationId: "16",
              mlid: "2604",
              url: "/ug-courses/online-bca/data-analytics",
              uids:["48","183",""],
            },
            {
              value: "6",
              name: "Artificial Intelligence and Machine Learning",
              extraEdgeSpecializationId: "17",
              mlid: "2605",
              url: "/ug-courses/online-bca/ai-and-machine-learning",
              uids:["239","661",""],
            },
            {
              value: "7",
              name: "Cloud and Security",
              extraEdgeSpecializationId: "18",
              mlid: "2606",
              url: "/ug-courses/online-bca/cloud-and-security",
              uids:["49",""],
            },
            {
              value: "8",
              name: "Cyber Security",
              extraEdgeSpecializationId: "19",
              mlid: "2607",
              url: "/ug-courses/online-bca/cyber-security",
              uids:["239","437","614","632",""],
            },
            {
              value: "9",
              name: "AI & Data Science",
              extraEdgeSpecializationId: "19",
              mlid: "2611",
              url: "/ug-courses/online-bca/ai-data-science",
              uids:["162",""],
            },
            {
              value: "10",
              name: "Blockchain Technology",
              extraEdgeSpecializationId: "19",
              mlid: "2612",
              url: "/ug-courses/online-bca/blockchain-technology",
              uids:["307",""],
            },
            {
              value: "11",
              name: "Cloud Security & Cyber Security",
              extraEdgeSpecializationId: "19",
              mlid: "2613",
              url: "/ug-courses/online-bca/cloud-security-cyber-security",
              uids:["181",""],
            },
            {
              value: "12",
              name: "Cloud Technoloy & Information System",
              extraEdgeSpecializationId: "19",
              mlid: "2614",
              url: "/ug-courses/online-bca/cloud-technology-information-system",
              uids:["306","486",""],
            },
            {
              value: "13",
              name: "Data Science",
              extraEdgeSpecializationId: "19",
              mlid: "2615",
              url: "/ug-courses/online-bca/data-science",
              uids:["240","305","389","404","487","660",""],
            },
            {
              value: "14",
              name: "Full Stack Development",
              extraEdgeSpecializationId: "19",
              mlid: "2616",
              url: "/ug-courses/online-bca/fullstack-development",
              uids:["241",""],
            },
            {
              value: "15",
              name: "Virtual & Augment Reality",
              extraEdgeSpecializationId: "19",
              mlid: "2617",
              url: "/ug-courses/online-bca/virtual-augment-reality",
              uids:["163",""],
            },
          ],
        },
        // {
        //   value: "4",
        //   name: "B.Tech for Working Professionals",
        //   clid: "8",
        //   extraEdgeCourseId: "1",
        //   mlid: null,
        //   redirectUrl: "/viewallpage/btech",
        //   specialization: [
           
            
        //     {
        //       value: "1",
        //       name: "Mechanical Engineering",
        //       extraEdgeSpecializationId: "5",
        //       mlid: "2802",
        //       url: "/ug-courses/online-distance-btech/mechincal-engineering",
        //     },
        //     {
        //       value: "2",
        //       name: "Computer Science Engineering",
        //       extraEdgeSpecializationId: "6",
        //       mlid: "2801",
        //       url: "/ug-courses/online-distance-btech/computer-science-engineering",
        //     },
        //     {
        //       value: "3",
        //       name: "Electrical Engineering",
        //       extraEdgeSpecializationId: "10",
        //       mlid: "2805",
        //       url: "/ug-courses/online-distance-btech/electrical-engineering",
        //     },
        //     {
        //       value: "4",
        //       name: "Civil Engineering",
        //       extraEdgeSpecializationId: "8",
        //       mlid: "2803",
        //       url: "/ug-courses/online-distance-btech/civil-engineering",
        //     },
        //     {
        //       value: "5",
        //       name: "Electronics Communication Engineering",
        //       extraEdgeSpecializationId: "9",
        //       mlid: "2804",
        //       url: "/ug-courses/online-distance-btech/electronics-communication-engineering",
        //     },
        //     {
        //       value: "6",
        //       name: "Machanical automobile Engineering",
        //       extraEdgeSpecializationId: "11",
        //       mlid: "2806",
        //       url: "/ug-courses/online-distance-btech/machanical-automobile-engineering",
        //     },
        //   ],
        // },
      ],
    },
  
    // pg Cources
    {
      value: "1",
      name: "PG Courses",
      url: "/viewallpgpage",
      elid: "3",
      subCourses: [
        {
          mlid: null,
          value: "0",
          name: "Online MBA",
          clid:"9",
          redirectUrl: "/viewallpgpage/mba",
          extraEdgeCourseId: "11",
          specialization: [
  
              {
                value: "1",
                name: "MBA General",
                extraEdgeSpecializationId: "60",
                mlid: "3900",
                url: "/pg-courses/online-mba/mba-general",
                uids:["266","383",""],
              },
              {
                value: "2",
                name: "Finance Management",
                extraEdgeSpecializationId: "61",
                mlid: "3901",
                url: "/pg-courses/online-mba/finance-management",
                uids:["3","57","75","86","128","176","186","202","216","226","244","274","289","318","343","364","274","394","416","456","701","636","673",""],
              },
              {
                  value: "3",
                  name: "HR Management",
                  extraEdgeSpecializationId: "62",
                  mlid: "3902",
                  url: "/pg-courses/online-mba/hr-management",
                  uids:["8","59","76","87","136","155","171","185","203","214","225","243","276","287","321","344","363","375","391","455","617","672",""],
                },
                {
                  value: "4",
                  name: "Hospitality Management",
                  extraEdgeSpecializationId: "63",
                  mlid: "3903",
                  url: "/pg-courses/online-mba/hospitality-management",
                  uids:["13","349",""],
                },
                {
                  value: "5",
                  name: "Banking & Finance Management",
                  extraEdgeSpecializationId: "65",
                  mlid: "3905",
                  url: "/pg-courses/online-mba/banking-finance",
                  uids:["103",""],
                },
                {
                  value: "6",
                  name: "Marketing and Finance Management (Dual)",
                  extraEdgeSpecializationId: "66",
                  mlid: "3906",
                  url: "/pg-courses/online-mba/marketing-and-finanace-management",
                  uids:["91",""],
                },
                {
                  value: "7",
                  name: "Information Technology Management",
                  extraEdgeSpecializationId: "67",
                  mlid: "3907",
                  url: "/pg-courses/online-mba/information-technology-management",
                  uids:["4","95","134","188","206","218","231","278","293","347","368","454",""],
                },
                {
                  value: "8",
                  name: "Logistics and Supply Chain Management (Dual)",
                  extraEdgeSpecializationId: "68",
                  mlid: "3908",
                  url: "/pg-courses/online-mba/logistic-supply-chain",
                  uids:["11","93","167","219","396","411","446","466","474","675",""],
                },
                {
                  value: "9",
                  name: "Marketing and HR Management (Dual)",
                  extraEdgeSpecializationId: "69",
                  mlid: "3909",
                  url: "/pg-courses/online-mba/marketing-and-hr-management",
                  uids:["92",""],
                },
                {
                  value: "10",
                  name: "Operations Management",
                  extraEdgeSpecializationId: "70",
                  mlid: "3910",
                  url: "/pg-courses/online-mba/operations-management",
                  uids:["12","63","130","154","173","189","246","292","346","366","415","452","467","621","674",""],
                },
                {
                  value: "11",
                  name: "Data Science and Analytics Management (Dual)",
                  extraEdgeSpecializationId: "71",
                  mlid: "3911",
                  url: "/pg-courses/online-mba/data-science-analytics",
                  uids:["60","101","233",""],
                },
                {
                  value: "12",
                  name: "Business Analytics",
                  extraEdgeSpecializationId: "72",
                  mlid: "3912",
                  url: "/pg-courses/online-mba/buisness-analytics",
                  uids:["35","131","169","191","204","215","277","392","453","498","619","678"],
                },
                {
                    value: "13",
                    name: "HRM and Finance Management (Dual)",
                    extraEdgeSpecializationId: "73",
                    mlid: "3913",
                    url: "/pg-courses/online-mba/hrm-finance-management",
                    uids:["90","205","472",""],
                  },
                  {
                    value: "14",
                    name: "Healthcare  Management",
                    extraEdgeSpecializationId: "74",
                    mlid: "3914",
                    url: "/pg-courses/online-mba/healthcare-Management",
                    uids:["96","290","407","444","621",""],
                  },
                  {
                    value: "15",
                    name: "Digital Marketing E Commerce Management",
                    extraEdgeSpecializationId: "75",
                    mlid: "3915",
                    url: "/pg-courses/online-mba/digital-marketing-management",
                    uids:["102","324","405",""],
                  },
                  {
                    value: "16",
                    name: "Business Management",
                    extraEdgeSpecializationId: "76",
                    mlid: "3916",
                    url: "/pg-courses/online-mba/business-management",
                    uids:[""],
                  },
                  {
                    value: "17",
                    name: "International Business Management",
                    extraEdgeSpecializationId: "77",
                    mlid: "3917",
                    url: "/pg-courses/online-mba/international-bussiness-management",
                    uids:["2","64","135","168","187","217","294","345","419","677",""],
                  },
                  {
                    value: "18",
                    name: "Project Management",
                    extraEdgeSpecializationId: "78",
                    mlid: "3918",
                    url: "/pg-courses/online-mba/project-Management",
                    uids:["66","94","448",""],
                  },
                  {
                    value: "19",
                    name: "Finance And Leadership Management (Dual)",
                    extraEdgeSpecializationId: "79",
                    mlid: "3919",
                    url: "/pg-courses/online-mba/finance-leadership",
                    uids:[""],
                  },
                  {
                    value: "20",
                    name: "Financial Markets Management",
                    extraEdgeSpecializationId: "80",
                    mlid: "3920",
                    url: "/pg-courses/online-mba/mba-financial-markets-management",
                    uids:[""],
                  },
                  {
                    value: "21",
                    name: "General Management",
                    extraEdgeSpecializationId: "81",
                    mlid: "0",
                    url: "/pg-courses/online-mba/general-management",
                    uids:["88","152",],
                  },
                  {
                    value: "22",
                    name: "Banking Financial Service Insurence",
                    extraEdgeSpecializationId: "82",
                    mlid: "3922",
                    url: "/pg-courses/online-mba/mba-banking-financial-service-insurence",
                    uids:["61","190","441",""],
                  },
                  {
                    value: "23",
                    name: "Entrepreneurship and Leadership (Dual)",
                    extraEdgeSpecializationId: "83",
                    mlid: "3923",
                    url: "/pg-courses/online-mba/entrepreneurship-leadership",
                    uids:["98",""],
                  },
                  {
                    value: "24",
                    name: "Business Intelligence and Analytics (Dual)",
                    extraEdgeSpecializationId: "84",
                    mlid: "3924",
                    url: "/pg-courses/online-mba/business-intelligence-analytics",
                    uids:["97","406",""],
                  },
                  {
                    value: "25",
                    name: "Advertising And branding (Dual)",
                    extraEdgeSpecializationId: "85",
                    mlid: "3925",
                    url: "/pg-courses/online-mba/mba-advertising-branding",
                    uids:[""],
                  },
                  {
                    value: "26",
                    name: "System and Operations Management (Dual)",
                    extraEdgeSpecializationId: "86",
                    mlid: "3926",
                    url: "/pg-courses/online-mba/system-and-operation-management",
                    uids:["89",],
                  },
                  {
                    value: "27",
                    name: "Hospital Administration",
                    extraEdgeSpecializationId: "87",
                    mlid: "3927",
                    url: "/pg-courses/online-mba/mba-hospital-administration",
                    uids:["348"],
                  },
                  {
                    value: "28",
                    name: "Business Intelligence & AI (Dual)",
                    extraEdgeSpecializationId: "88",
                    mlid: "3928",
                    url: "/pg-courses/online-mba/mba-business-intelligence",
                    uids:[""],
                  },
                  {
                    value: "29",
                    name: "Oil and Gas Management (Dual)",
                    extraEdgeSpecializationId: "89",
                    mlid: "3929",
                    url: "/pg-courses/online-mba/mba-oil-and-gas-management",
                    uids:["174",""],
                  },
                  {
                    value: "30",
                    name: "International Trade Manangement",
                    extraEdgeSpecializationId: "90",
                    mlid: "3930",
                    url: "/pg-courses/online-mba/mba-international-trade-management",
                    uids:[""],
                  },
                  {
                    value: "31",
                    name: "Fintech Manangement",
                    extraEdgeSpecializationId: "91",
                    mlid: "3931",
                    url: "/pg-courses/online-mba/mba-fintech-management",
                    uids:["302",""],
                  },
                  {
                    value: "32",
                    name: "Retail Manangement",
                    extraEdgeSpecializationId: "92",
                    mlid: "3932",
                    url: "/pg-courses/online-mba/mba-retail-management",
                    uids:["5","192","228","301","382","450","601",],
                  },
                  {
                    value: "33",
                    name: "Tourism Manangement",
                    extraEdgeSpecializationId: "93",
                    mlid: "3933",
                    url: "/pg-courses/online-mba/mba-tourism-management",
                    uids:["232",""],
                  },
                  {
                    value: "34",
                    name: "Investment Banking Equity Research Management",
                    extraEdgeSpecializationId: "94",
                    mlid: "3934",
                    url: "/pg-courses/online-mba/mba-investment-banking-equity-research-management",
                    uids:[""],
                  },
                  {
                    value: "35",
                    name: "International Finance Management",
                    extraEdgeSpecializationId: "95",
                    mlid: "3935",
                    url: "/pg-courses/online-mba/international-finance",
                    uids:["32","99",""],
                  },
                  {
                    value: "36",
                    name: "Power Management",
                    extraEdgeSpecializationId: "96",
                    mlid: "3936",
                    url: "/pg-courses/online-mba/mba-powermanagement",
                    uids:["175",""],
                  },
                  {
                    value: "37",
                    name: "Sports Manangement",
                    extraEdgeSpecializationId: "97",
                    mlid: "3937",
                    url: "/pg-courses/online-mba/mba-sports-management",
                    uids:[""],
                  },
                  {
                    value: "38",
                    name: "HR Analytics",
                    extraEdgeSpecializationId: "98",
                    mlid: "3938",
                    url: "/pg-courses/online-mba/mba-hr-analytics",
                    uids:["37",""],
                  },
                  {
                    value: "39",
                    name: "Digital Entrepreneurship",
                    extraEdgeSpecializationId: "99",
                    mlid: "3939",
                    url: "/pg-courses/online-mba/mba-digital-entrepreneurship",
                    uids:["9","34",""],
                  },
                  {
                    value: "40",
                    name: "Leadership and Strategey (Dual)",
                    extraEdgeSpecializationId: "100",
                    mlid: "3940",
                    url: "/pg-courses/online-mba/leadership-and-stragey",
                    uids:[""],
                  },
                  {
                    value: "41",
                    name: "Strategic HR Management",
                    extraEdgeSpecializationId: "101",
                    mlid: "3941",
                    url: "/pg-courses/online-mba/mba-startegic-hr-management",
                    uids:[""],
                  },
                  {
                    value: "42",
                    name: "Banking And Insurance",
                    extraEdgeSpecializationId: "102",
                    mlid: "3942",
                    url: "/pg-courses/online-mba/mba-banking-insurance",
                    uids:["6","229","414",""],
                  },
                  {
                    value: "43",
                    name: "Strategic Markeing",
                    extraEdgeSpecializationId: "103",
                    mlid: "3943",
                    url: "/pg-courses/online-mba/mba-strategic-marketing",
                    uids:[""],
                  },
                  {
                    value: "44",
                    name: "Strategic Finance Management",
                    extraEdgeSpecializationId: "104",
                    mlid: "3944",
                    url: "/pg-courses/online-mba/mba-strategic-finance-management",
                    uids:[""],
                  },
                  {
                    value: "45",
                    name: "International Marketing Management",
                    extraEdgeSpecializationId: "105",
                    mlid: "3945",
                    url: "/pg-courses/online-mba/mba-international-marketing-management",
                    uids:[""],
                  },
                  {
                    value: "46",
                    name: "Artificial Intelligence and Machine Learning (Dual)",
                    extraEdgeSpecializationId: "106",
                    mlid: "3946",
                    url: "/pg-courses/online-mba/mba-ai-machine-learning",
                    uids:[""],
                  },
                  {
                    value: "47",
                    name: "BlockChain Management",
                    extraEdgeSpecializationId: "107",
                    mlid: "3947",
                    url: "/pg-courses/online-mba/mba-blockChain-management",
                    uids:[""],
                  },
                  {
                    value: "48",
                    name: "Waste Management",
                    extraEdgeSpecializationId: "108",
                    mlid: "3948",
                    url: "/pg-courses/online-mba/mba-waste-management",
                    uids:["417",""],
                  },
                  {
                    value: "49",
                    name: "IT and FineTech (Dual)",
                    extraEdgeSpecializationId: "109",
                    mlid: "3949",
                    url: "/pg-courses/online-mba/mba-it-and-fintech",
                    uids:["62",""],
                  },
                  {
                    value: "50",
                    name: "Marketing Management",
                    extraEdgeSpecializationId: "109",
                    mlid: "3950",
                    url: "/pg-courses/online-mba/marketing",
                    uids:["1","172","184","201","212","224","245","275","288","322","342","365","373","393","412","457","465","473","58","74","85","129","153","616","671",""],
                  },
                  {
                    value: "51",
                    name: "Artificial Intelligence",
                    extraEdgeSpecializationId: "109",
                    mlid: "3951",
                    url: "/pg-courses/online-mba/artificial-intelligence",
                    uids:["106","150",""],
                  },
                  {
                    value: "52",
                    name: "Data Science",
                    extraEdgeSpecializationId: "109",
                    mlid: "3952",
                    url: "/pg-courses/online-mba/data-science",
                    uids:["36","133","475","620",""],
                  },
                  {
                    value: "53",
                    name: "Entrepreneurship",
                    extraEdgeSpecializationId: "109",
                    mlid: "3953",
                    url: "/pg-courses/online-mba/entrepreneurship",
                    uids:["9","477",""],
                  },
                  {
                    value: "54",
                    name: "Event Management",
                    extraEdgeSpecializationId: "109",
                    mlid: "3954",
                    url: "/pg-courses/online-mba/event-management",
                    uids:["7",""],
                  },
                  {
                    value: "55",
                    name: "Information Technology",
                    extraEdgeSpecializationId: "109",
                    mlid: "3955",
                    url: "/pg-courses/online-mba/information-technology",
                    uids:["4","95","134","188","206","218","231","278","293","347","368",""],
                  },
                  {
                    value: "56",
                    name: "Disaster Management",
                    extraEdgeSpecializationId: "109",
                    mlid: "3956",
                    url: "/pg-courses/online-mba/disaster-management",
                    uids:["10",""],
                  },
                  {
                    value: "57",
                    name: "Digital Marketing",
                    extraEdgeSpecializationId: "109",
                    mlid: "3957",
                    url: "/pg-courses/online-mba/digital-marketing",
                    uids:["602",],
                  },
                  {
                    value: "58",
                    name: "Supply Chain Management",
                    extraEdgeSpecializationId: "109",
                    mlid: "3958",
                    url: "/pg-courses/online-mba/supply-chain-management",
                    uids:["193",""],
                  },
                  {
                    value: "59",
                    name: "System Management",
                    extraEdgeSpecializationId: "109",
                    mlid: "3959",
                    url: "/pg-courses/online-mba/system-management",
                    uids:["77",""],
                  },
                  {
                    value: "60",
                    name: "Operation & Supply Chain",
                    extraEdgeSpecializationId: "109",
                    mlid: "3960",
                    url: "/pg-courses/online-mba/operation-supply-chain",
                    uids:["230",""],
                  },
                  {
                    value: "61",
                    name: "International Finance & Accounting",
                    extraEdgeSpecializationId: "109",
                    mlid: "3961",
                    url: "/pg-courses/online-mba/international-finance-accounting",
                    uids:[""],
                  },
                  {
                    value: "62",
                    name: "Digital Business",
                    extraEdgeSpecializationId: "109",
                    mlid: "3962",
                    url: "/pg-courses/online-mba/digital-business",
                    uids:["170",""],
                  },
                  {
                    value: "63",
                    name: "Infrastructure Management",
                    extraEdgeSpecializationId: "109",
                    mlid: "3963",
                    url: "/pg-courses/online-mba/infrastructure-management",
                    uids:["174",""],
                  },
                  {
                    value: "64",
                    name: "Healthcare & Hospital Management",
                    extraEdgeSpecializationId: "109",
                    mlid: "3964",
                    url: "/pg-courses/online-mba/healthcare-hospital-management",
                    uids:["207","247","326","367","397","679",""],
                  },
                  {
                    value: "65",
                    name: "Computer Science & IT",
                    extraEdgeSpecializationId: "109",
                    mlid: "3965",
                    url: "/pg-courses/online-mba/computer-science-it",
                    uids:[""],
                  },
                  {
                    value: "66",
                    name: "Travel & Tourism Management",
                    extraEdgeSpecializationId: "109",
                    mlid: "3966",
                    url: "/pg-courses/online-mba/travel-tourism-management",
                    uids:["14",""],
                  },
                  {
                    value: "67",
                    name: "Agri Business Management",
                    extraEdgeSpecializationId: "109",
                    mlid: "3967",
                    url: "/pg-courses/online-mba/agri-business-management",
                    uids:["234","291","350","440",""],
                  },
                  {
                    value: "68",
                    name: "Pharma & Healthcare Management",
                    extraEdgeSpecializationId: "109",
                    mlid: "3968",
                    url: "/pg-courses/online-mba/pharma-healthcare-management",
                    uids:["235",""],
                  },
                  {
                    value: "69",
                    name: "Finance & Accounting",
                    extraEdgeSpecializationId: "109",
                    mlid: "3969",
                    url: "/pg-courses/online-mba/finance-accounting",
                    uids:["377",""],
                  },
                  {
                    value: "70",
                    name: "Data Science & AI",
                    extraEdgeSpecializationId: "109",
                    mlid: "3970",
                    url: "/pg-courses/online-mba/data-science-ai",
                    uids:["378","395",""],
                  },
                  {
                    value: "71",
                    name: "Wealth Management",
                    extraEdgeSpecializationId: "109",
                    mlid: "3971",
                    url: "/pg-courses/online-mba/wealth-management",
                    uids:["379",""],
                  },
                  {
                    value: "72",
                    name: "Cyber Security",
                    extraEdgeSpecializationId: "109",
                    mlid: "3972",
                    url: "/pg-courses/online-mba/cyber-security",
                    uids:["381",""],
                  },
                  {
                    value: "73",
                    name: "Entrepreneurship & Business Management",
                    extraEdgeSpecializationId: "109",
                    mlid: "3973",
                    url: "/pg-courses/online-mba/entrepreneurship-business-management",
                    uids:["409",""],
                  },
                  {
                    value: "74",
                    name: "Event & Media Management",
                    extraEdgeSpecializationId: "109",
                    mlid: "3974",
                    url: "/pg-courses/online-mba/event-media-management",
                    uids:["418",""],
                  },
                  // {
                  //   value: "75",
                  //   name: "Public Policy & Administration",
                  //   extraEdgeSpecializationId: "109",
                  //   mlid: "3975",
                  //   url: "/pg-courses/online-mba/public-policy-administration",
                  //   uids:[""],
                  // },
                  {
                    value: "76",
                    name: "International & Trade Business",
                    extraEdgeSpecializationId: "109",
                    mlid: "3976",
                    url: "/pg-courses/online-mba/international-trade-business",
                    uids:["445",""],
                  },
                  // {
                  //   value: "77",
                  //   name: "JAMC",
                  //   extraEdgeSpecializationId: "109",
                  //   mlid: "3977",
                  //   url: "/pg-courses/online-mba/jamc",
                  //   uids:[""],
                  // },
                  {
                    value: "78",
                    name: "Organizational Behaviour",
                    extraEdgeSpecializationId: "109",
                    mlid: "3978",
                    url: "/pg-courses/online-mba/organizational-behaviour",
                    uids:[""],
                  },
  
            ],
        },
        {
          mlid: null,
          value: "1",
          name: "Online MCA",
          clid: "10",
          extraEdgeCourseId: "12",
          redirectUrl: "/viewallpgpage/mca",
          specialization: [
            {
              value: "0",
              name: "General",
              mlid: "51623",
              url: "/pg-courses/online-mca/mca-general",
              uids:["83","156","194","220","249","279","351","369","384","398","458","468","478","656",""],
            },
            {
              value: "1",
              name: "Cyber Security",
              extraEdgeSpecializationId: "111",
              mlid: "31002",
              url: "/pg-courses/online-mca/cyber-security",
              uids:["70","109","140","158","482","627",""],
            },
            {
              value: "2",
              name: "Data Science",
              extraEdgeSpecializationId: "112",
              mlid: "31003",
              url: "/pg-courses/online-mca/data-science",
              uids:["111","139","209","331","480","652",],
            },
            {
              value: "3",
              name: "Cloud Computing",
              extraEdgeSpecializationId: "113",
              mlid: "31004",
              url: "/pg-courses/online-mca/cloud-computing",
              uids:["16","69","481","626","629",],
            },
            {
              value: "4",
              name: "Artificial Intelligence",
              extraEdgeSpecializationId: "114",
              mlid: "31005",
              url: "/pg-courses/online-mca/artificial-intelligence",
              uids:["68","112","157","295","479",""],
            },
            {
              value: "5",
              name: "Game Development",
              extraEdgeSpecializationId: "116",
              mlid: "31007",
              url: "/pg-courses/online-mca/game-development",
              uids:[""],
            },
            {
              value: "6",
              name: "Artificial Intelligence and Machine Learning",
              extraEdgeSpecializationId: "117",
              mlid: "31008",
              url: "/pg-courses/online-mca/artificial-intelligence-and-machine-learning",
              uids:["19","39","138","625","641","651",""],
            },
            {
              value: "7",
              name: "Data Analytics",
              extraEdgeSpecializationId: "115",
              mlid: "31006",
              url: "/pg-courses/online-mca/data-analytics",
              uids:["17","71","108",""],
            },
            {
              value: "8",
              name: "Computer Science And IT",
              extraEdgeSpecializationId: "110",
              mlid: "31001",
              url: "/pg-courses/online-mca/computer-science-and-it",
              uids:["107","208","330",""],
            },
            {
              value: "9",
              name: "Reality and Virtual Reality",
              extraEdgeSpecializationId: "122",
              mlid: "31013",
              url: "/pg-courses/online-mca/augmented-reality-and-virtual-reality",
              uids:["40",""],
            },
            {
              value: "10",
              name: "Machine Learning",
              extraEdgeSpecializationId: "121",
              mlid: "31012",
              url: "/pg-courses/online-mca/machine-learning",
              uids:[""],
            },
            {
              value: "11",
              name: "Block chain",
              extraEdgeSpecializationId: "120",
              mlid: "31011",
              url: "/pg-courses/online-mca/blockchain",
              uids:["38",""],
            },
            {
              value: "12",
              name: "Data Science and BigData Analytics",
              extraEdgeSpecializationId: "119",
              mlid: "31010",
              url: "/pg-courses/online-mca/data-science-and-big-data-analytics",
              uids:[""],
            },
            {
              value: "13",
              name: "AR/VR Game Development",
              extraEdgeSpecializationId: "119",
              mlid: "31023",
              url: "/pg-courses/online-mca/ar-vr-game-development",
              uids:["40","137",""],
            },
            {
              value: "15",
              name: "Cyber Security & Blockchain",
              extraEdgeSpecializationId: "119",
              mlid: "31025",
              url: "/pg-courses/online-mca/cyber-security-blockchain",
              uids:["420",""],
            },
            {
              value: "16",
              name: "AI & Data Science",
              extraEdgeSpecializationId: "119",
              mlid: "31026",
              url: "/pg-courses/online-mca/data-science-ai",
              uids:["422",""],
            },
            {
              value: "12",
              name: "Fullstack Development",
              extraEdgeSpecializationId: "119",
              mlid: "31027",
              url: "/pg-courses/online-mca/fullstack-development",
              uids:["18","110","141","628","653",""],
            },
  
  
  
   
          ],
        },
        {
          mlid: null,
          value: "2",
          name: "Online M.Com",
          clid: "13",
          extraEdgeCourseId: "15",
          redirectUrl: "/viewallpgpage/mcom",
          specialization: [
            {
              value: "1",
              name: "M.Com General",
              extraEdgeSpecializationId: "139",
              mlid: "31301",
              url: "/pg-courses/online-mcom/mcom-general",
              uids:["142","256","280","460","249",""],
            },
            {
              value: "2",
              name: "Finance Management",
              extraEdgeSpecializationId: "143",
              mlid: "31305",
              url: "/pg-courses/online-mcom/finance-management",
              uids:["44","399",""],
            },
            {
              value: "3",
              name: "Accounting and Finance",
              extraEdgeSpecializationId: "140",
              mlid: "31302",
              url: "/pg-courses/online-mcom/account-finance",
              uids:["113"],
            },
            {
              value: "4",
              name: "International Finance",
              extraEdgeSpecializationId: "142",
              mlid: "31304",
              url: "/pg-courses/online-mcom/international-finance",
              uids:["115",""],
            },
            {
              value: "5",
              name: "Professional Accounting And Finance",
              extraEdgeSpecializationId: "141",
              mlid: "31303",
              url: "/pg-courses/online-mcom/professional-accounting-finance",
              uids:["114",""],
            },
            // {
            //   value: "6",
            //   name: "Fintech",
            //   extraEdgeSpecializationId: "144",
            //   mlid: "31306",
            //   url: "/pg-courses/online-mcom/fintech",
            //   uids:[""],
            // },
            {
              value: "7",
              name: "Business Analytics",
              extraEdgeSpecializationId: "144",
              mlid: "31309",
              url: "/pg-courses/online-mcom/business-analytics",
              uids:["402","428",""],
            },
            {
              value: "8",
              name: "Finance & System",
              extraEdgeSpecializationId: "144",
              mlid: "31310",
              url: "/pg-courses/online-mcom/finance-system",
              uids:["159",""],
            },
            {
              value: "9",
              name: "HR Management",
              extraEdgeSpecializationId: "144",
              mlid: "31311",
              url: "/pg-courses/online-mcom/hr-management",
              uids:["400",""],
            },
            {
              value: "10",
              name: "International Finance & Accounting",
              extraEdgeSpecializationId: "144",
              mlid: "31312",
              url: "/pg-courses/online-mcom/international-finance-accounting",
              uids:["160",""],
            },
            {
              value: "11",
              name: "Marketing",
              extraEdgeSpecializationId: "144",
              mlid: "31313",
              url: "/pg-courses/online-mcom/marketing",
              uids:["401",""],
            },
           
          ],
        },
        {
          mlid: null,
          value: "3",
          name: "Online MA",
          clid: "17",
          extraEdgeCourseId: "19",
          redirectUrl: "/viewallpgpage/ma",
          specialization: [
            {
              value: "9",
              name: "General",
              extraEdgeSpecializationId: "191",
              mlid: "31711",
              url: "/pg-courses/online-ma/general",
              uids:["459",""],
            },
            {
              value: "1",
              name: "Economics",
              extraEdgeSpecializationId: "189",
              mlid: "31702",
              url: "/pg-courses/online-ma/economics",
              uids:["21","253","258","267",""],
            },
            {
              value: "2",
              name: "Journalism and Mass Communication",
              extraEdgeSpecializationId: "192",
              mlid: "31705",
              url: "/pg-courses/online-ma/journalism-mass-communication",
              uids:["22","41","261",""],
            },
            {
              value: "3",
              name: "English",
              extraEdgeSpecializationId: "188",
              mlid: "31701",
              url: "/pg-courses/online-ma/english",
              uids:["20","84","143","236","250","259","268","282","298","429",""],
            },
            {
              value: "4",
              name: "Psychology",
              mlid: "51622",
              url: "/pg-courses/online-ma/psychology",
              uids:["42",""],
            },
  
  
            {
              value: "5",
              name: "Public Policy Administration",
              extraEdgeSpecializationId: "194",
              mlid: "31707",
              url: "/pg-courses/online-ma/public-policy-administration",
              uids:["43","252","269",""],
            },
            {
              value: "6",
              name: "Sociology",
              extraEdgeSpecializationId: "193",
              mlid: "31706",
              url: "/pg-courses/online-ma/sociology",
              uids:["145",""],
            },
            {
              value: "7",
              name: "History",
              extraEdgeSpecializationId: "190",
              mlid: "31703",
              url: "/pg-courses/online-ma/history",
              uids:["144","271",""],
            },
            {
              value: "8",
              name: "Political Science",
              extraEdgeSpecializationId: "191",
              mlid: "31704",
              url: "/pg-courses/online-ma/political-science",
              uids:["146","251","257","270","283","385",""],
            },
            
            {
              value: "11",
              name: "Mass Communication",
              extraEdgeSpecializationId: "191",
              mlid: "31713",
              url: "/pg-courses/online-ma/mass-communication",
              uids:["495","281",""],
            },
          ],
        },
        // {
        //   mlid: null,
        //   value: "4",
        //   name: "M.Tech for Working Professionals",
        //   clid: "12",
        //   extraEdgeCourseId: "14",
        //   redirectUrl: "/viewallpgpage/mtech",
        //   specialization: [
        //     {
        //       value: "1",
        //       name: "Mechanical Production",
        //       extraEdgeSpecializationId: "138",
        //       mlid: "31210",
        //       url: "/pg-courses/online-distance-mtech/mechincal-production",
        //     },
        //     {
        //       value: "2",
        //       name: "Computer Science Engineering",
        //       extraEdgeSpecializationId: "130",
        //       mlid: "31202",
        //       url: "/pg-courses/online-distance-mtech/computer-science-engineering",
        //     },
        //     {
        //       value: "3",
        //       name: "Civil Engineering",
        //       extraEdgeSpecializationId: "134",
        //       mlid: "31206",
        //       url: "/pg-courses/online-distance-mtech/civil-engineering",
        //     },
        //     {
        //       value: "4",
        //       name: "Electrical Power System",
        //       extraEdgeSpecializationId: "137",
        //       mlid: "31209",
        //       url: "/pg-courses/online-distance-mtech/electrical-power-system",
        //     },
        //     {
        //       value: "5",
        //       name: "Civil Structural",
        //       extraEdgeSpecializationId: "131",
        //       mlid: "31203",
        //       url: "/pg-courses/online-distance-mtech/civil-structural",
        //     },
        //     {
        //       value: "6",
        //       name: "Mechanical Design",
        //       extraEdgeSpecializationId: "135",
        //       mlid: "31207",
        //       url: "/pg-courses/online-distance-mtech/mechanical-design",
        //     },
        //   ],
        // },
        {
          mlid: null,
          value: "5",
          name: "Online M.Sc",
          clid: "11",
          extraEdgeCourseId: "13",
          redirectUrl: "/viewallpgpage/msc",
          specialization: [
            {
              value: "1",
              name: "General",
              extraEdgeSpecializationId: "123",
              mlid: "31101",
              url: "/pg-courses/online-msc/general",
              uids:[""],
            },
            {
              value: "2",
              name: "Business Analytics",
              extraEdgeSpecializationId: "128",
              mlid: "31106",
              url: "/pg-courses/online-msc/business-analytics",
              uids:[""],
            },
            {
              value: "3",
              name: "AI and Machine Learning",
              extraEdgeSpecializationId: "126",
              mlid: "31104",
              url: "/pg-courses/online-msc/ai-machine-learning",
              uids:[""],
            },
            {
              value: "4",
              name: "Applied Finance",
              extraEdgeSpecializationId: "127",
              mlid: "31105",
              url: "/pg-courses/online-msc/applied-finance",
              uids:[""],
            },
            {
              value: "5",
              name: "Data Science",
              extraEdgeSpecializationId: "125",
              mlid: "31103",
              url: "/pg-courses/online-msc/data-science",
              uids:["23","45","79","341","492",""],
            },
            {
              value: "6",
              name: "Mathematics",
              extraEdgeSpecializationId: "124",
              mlid: "31102",
              url: "/pg-courses/online-msc/mathematics",
              uids:["24","147","297","461",],
            },
            {
              value: "7",
              name: "Computer Application",
              extraEdgeSpecializationId: "124",
              mlid: "31110",
              url: "/pg-courses/online-msc/computer-application",
              uids:["493",""],
            },
          ],
        },
        // {
        //   mlid: null,
        //   value: "6",
        //   name: "Distance MBA",
        //   clid:"50",
        //   redirectUrl: "/viewallpgpage/mba",
        //   extraEdgeCourseId: "71",
        //   specialization: [
  
        //       {
        //         value: "1",
        //         name: "MBA General",
        //         extraEdgeSpecializationId: "60",
        //         mlid: "6100",
        //         url: "/pg-courses/distance-mba/mba-general",
        //       },
        //       {
        //         value: "2",
        //         name: "Finance Management",
        //         extraEdgeSpecializationId: "61",
        //         mlid: "6101",
        //         url: "/pg-courses/distance-mba/finanace-management",
        //       },
        //       {
        //           value: "3",
        //           name: "HR Management",
        //           extraEdgeSpecializationId: "62",
        //           mlid: "6102",
        //           url: "/pg-courses/distance-mba/hr-management",
        //         },
        //         {
        //           value: "4",
        //           name: "Hospitality Management",
        //           extraEdgeSpecializationId: "63",
        //           mlid: "6103",
        //           url: "/pg-courses/distance-mba/hospitality-management",
        //         },
        //         {
        //           value: "5",
        //           name: "Banking & Finance Management",
        //           extraEdgeSpecializationId: "65",
        //           mlid: "6105",
        //           url: "/pg-courses/distance-mba/banking-finance",
        //         },
        //         {
        //           value: "6",
        //           name: "Marketing and Finance Management (Dual)",
        //           extraEdgeSpecializationId: "66",
        //           mlid: "6106",
        //           url: "/pg-courses/distance-mba/marketing-and-finanace-management",
        //         },
        //         {
        //           value: "7",
        //           name: "Information Technology Management",
        //           extraEdgeSpecializationId: "67",
        //           mlid: "6107",
        //           url: "/pg-courses/distance-mba/information-technology-management",
        //         },
        //         {
        //           value: "8",
        //           name: "Logistics and Supply Chain Management (Dual)",
        //           extraEdgeSpecializationId: "68",
        //           mlid: "6108",
        //           url: "/pg-courses/distance-mba/logistic-supply-chain",
        //         },
        //         {
        //           value: "9",
        //           name: "Marketing and HR Management (Dual)",
        //           extraEdgeSpecializationId: "69",
        //           mlid: "6109",
        //           url: "/pg-courses/distance-mba/marketing-and-hr-management",
        //         },
        //         {
        //           value: "10",
        //           name: "Operations Management",
        //           extraEdgeSpecializationId: "70",
        //           mlid: "6110",
        //           url: "/pg-courses/distance-mba/operations-management",
        //         },
        //         {
        //           value: "11",
        //           name: "Data Science and Analytics Management (Dual)",
        //           extraEdgeSpecializationId: "71",
        //           mlid: "6111",
        //           url: "/pg-courses/distance-mba/data-science-analytics",
        //         },
        //         {
        //           value: "12",
        //           name: "Business Analytics",
        //           extraEdgeSpecializationId: "72",
        //           mlid: "6112",
        //           url: "/pg-courses/distance-mba/buisness-analytics",
        //         },
        //         {
        //             value: "13",
        //             name: "HRM and Finance Management (Dual)",
        //             extraEdgeSpecializationId: "73",
        //             mlid: "6113",
        //             url: "/pg-courses/distance-mba/hrm-finance-management",
        //           },
        //           {
        //             value: "14",
        //             name: "Healthcare  Management",
        //             extraEdgeSpecializationId: "74",
        //             mlid: "6114",
        //             url: "/pg-courses/distance-mba/healthcare-Management",
        //           },
        //           {
        //             value: "15",
        //             name: "Digital Marketing E Commerce Management",
        //             extraEdgeSpecializationId: "75",
        //             mlid: "6115",
        //             url: "/pg-courses/distance-mba/digital-marketing-management",
        //           },
        //           {
        //             value: "16",
        //             name: "Buisness Management",
        //             extraEdgeSpecializationId: "76",
        //             mlid: "6116",
        //             url: "/pg-courses/distance-mba/buisness-management",
        //           },
        //           {
        //             value: "17",
        //             name: "International Business Management",
        //             extraEdgeSpecializationId: "77",
        //             mlid: "6117",
        //             url: "/pg-courses/distance-mba/international-bussiness-management",
        //           },
        //           {
        //             value: "18",
        //             name: "Project Management",
        //             extraEdgeSpecializationId: "78",
        //             mlid: "6118",
        //             url: "/pg-courses/distance-mba/project-Management",
        //           },
        //           {
        //             value: "19",
        //             name: "Finance And Leadership Management (Dual)",
        //             extraEdgeSpecializationId: "79",
        //             mlid: "6119",
        //             url: "/pg-courses/distance-mba/finance-leadership",
        //           },
        //           {
        //             value: "20",
        //             name: "Financial Markets Management",
        //             extraEdgeSpecializationId: "80",
        //             mlid: "6120",
        //             url: "/pg-courses/distance-mba/mba-financial-markets-management",
        //           },
        //           {
        //             value: "22",
        //             name: "Banking Financial Service Insurence",
        //             extraEdgeSpecializationId: "82",
        //             mlid: "6122",
        //             url: "/pg-courses/distance-mba/mba-banking-financial-service-insurence",
        //           },
        //           {
        //             value: "23",
        //             name: "Entrepreneurship and Leadership (Dual)",
        //             extraEdgeSpecializationId: "83",
        //             mlid: "6123",
        //             url: "/pg-courses/distance-mba/entrepreneurship-leadership",
        //           },
        //           {
        //             value: "24",
        //             name: "Business Intelligence and Analytics (Dual)",
        //             extraEdgeSpecializationId: "84",
        //             mlid: "6124",
        //             url: "/pg-courses/distance-mba/business-intelligence-analytics",
        //           },
        //           {
        //             value: "25",
        //             name: "Advertising And branding (Dual)",
        //             extraEdgeSpecializationId: "85",
        //             mlid: "6125",
        //             url: "/pg-courses/distance-mba/mba-advertising-branding",
        //           },
        //           {
        //             value: "26",
        //             name: "System and Operations Management (Dual)",
        //             extraEdgeSpecializationId: "86",
        //             mlid: "6126",
        //             url: "/pg-courses/distance-mba/system-and-operation-management",
        //           },
        //           {
        //             value: "27",
        //             name: "Hospital Administration",
        //             extraEdgeSpecializationId: "87",
        //             mlid: "6127",
        //             url: "/pg-courses/distance-mba/mba-hospital-administration",
        //           },
        //           {
        //             value: "28",
        //             name: "Business Intelligence & AI (Dual)",
        //             extraEdgeSpecializationId: "88",
        //             mlid: "6128",
        //             url: "/pg-courses/distance-mba/mba-business-intelligence",
        //           },
        //           {
        //             value: "29",
        //             name: "Oil and Gas Management (Dual)",
        //             extraEdgeSpecializationId: "89",
        //             mlid: "6129",
        //             url: "/pg-courses/distance-mba/mba-oil-and-gas-management",
        //           },
        //           {
        //             value: "30",
        //             name: "International Trade Manangement",
        //             extraEdgeSpecializationId: "90",
        //             mlid: "6130",
        //             url: "/pg-courses/distance-mba/mba-international-trade-management",
        //           },
        //           {
        //             value: "31",
        //             name: "Fintech Manangement",
        //             extraEdgeSpecializationId: "91",
        //             mlid: "6131",
        //             url: "/pg-courses/distance-mba/mba-fintech-management",
        //           },
        //           {
        //             value: "32",
        //             name: "Retail Manangement",
        //             extraEdgeSpecializationId: "92",
        //             mlid: "6132",
        //             url: "/pg-courses/distance-mba/mba-retail-management",
        //           },
        //           {
        //             value: "33",
        //             name: "Tourism Manangement",
        //             extraEdgeSpecializationId: "93",
        //             mlid: "6133",
        //             url: "/pg-courses/distance-mba/mba-tourism-management",
        //           },
        //           {
        //             value: "34",
        //             name: "Investment Banking Equity Research Management",
        //             extraEdgeSpecializationId: "94",
        //             mlid: "6134",
        //             url: "/pg-courses/distance-mba/mba-investment-banking-equity-research-management",
        //           },
        //           {
        //             value: "35",
        //             name: "International Finance Management",
        //             extraEdgeSpecializationId: "95",
        //             mlid: "6135",
        //             url: "/pg-courses/distance-mba/international-finance",
        //           },
        //           {
        //             value: "36",
        //             name: "Power Managemnet",
        //             extraEdgeSpecializationId: "96",
        //             mlid: "6136",
        //             url: "/pg-courses/distance-mba/mba-powermanagemnet",
        //           },
        //           {
        //             value: "37",
        //             name: "Sports Manangement",
        //             extraEdgeSpecializationId: "97",
        //             mlid: "6137",
        //             url: "/pg-courses/distance-mba/mba-sports-management",
        //           },
        //           {
        //             value: "38",
        //             name: "HR Analytics",
        //             extraEdgeSpecializationId: "98",
        //             mlid: "6138",
        //             url: "/pg-courses/distance-mba/mba-hr-analytics",
        //           },
        //           {
        //             value: "39",
        //             name: "Digital Entrepreneurship ",
        //             extraEdgeSpecializationId: "99",
        //             mlid: "6161",
        //             url: "/pg-courses/distance-mba/mba-digital-entrepreneurship",
        //           },
        //           {
        //             value: "40",
        //             name: "Leadership and Strategey (Dual)",
        //             extraEdgeSpecializationId: "100",
        //             mlid: "6140",
        //             url: "/pg-courses/distance-mba/leadership-and-stragey",
        //           },
        //           {
        //             value: "41",
        //             name: "Strategic HR Management",
        //             extraEdgeSpecializationId: "101",
        //             mlid: "6141",
        //             url: "/pg-courses/distance-mba/mba-startegic-hr-management",
        //           },
        //           {
        //             value: "42",
        //             name: "Banking And Insurance",
        //             extraEdgeSpecializationId: "102",
        //             mlid: "6142",
        //             url: "/pg-courses/distance-mba/mba-banking-insurance",
        //           },
        //           {
        //             value: "43",
        //             name: "Strategic Markeing",
        //             extraEdgeSpecializationId: "103",
        //             mlid: "6143",
        //             url: "/pg-courses/distance-mba/mba-strategic-marketing",
        //           },
        //           {
        //             value: "44",
        //             name: "Strategic Finance Management",
        //             extraEdgeSpecializationId: "104",
        //             mlid: "6144",
        //             url: "/pg-courses/distance-mba/mba-strategic-finance-management",
        //           },
        //           {
        //             value: "45",
        //             name: "International Marketing Management",
        //             extraEdgeSpecializationId: "105",
        //             mlid: "6145",
        //             url: "/pg-courses/distance-mba/mba-international-marketing-management",
        //           },
        //           {
        //             value: "46",
        //             name: "Artificial Intelligence and Machine Learning (Dual)",
        //             extraEdgeSpecializationId: "106",
        //             mlid: "6146",
        //             url: "/pg-courses/distance-mba/mba-ai-machine-learning",
        //           },
        //           {
        //             value: "47",
        //             name: "BlockChain Management ",
        //             extraEdgeSpecializationId: "107",
        //             mlid: "6147",
        //             url: "/pg-courses/distance-mba/mba-blockChain-management",
        //           },
        //           {
        //             value: "48",
        //             name: "waste Management ",
        //             extraEdgeSpecializationId: "108",
        //             mlid: "6148",
        //             url: "/pg-courses/distance-mba/mba-waste-management",
        //           },
        //           {
        //             value: "49",
        //             name: "IT and FineTech (Dual)",
        //             extraEdgeSpecializationId: "109",
        //             mlid: "6149",
        //             url: "/pg-courses/distance-mba/mba-it-and-fintech",
        //           },
  
        //     ],
        // },
      ],
    },
  
    //Diploma
    // {
    //   value: "2",
    //   name: "Diploma",
    //   elid: "4",
    //   clid: "15",
    //   extraEdgeCourseId: "17",
    //   subCourses:  [
    //           {
    //             value: "1",
    //             name: "Banking & Finance",
    //             extraEdgeSpecializationId: "152",
    //             mlid: "41500",
    //             clid: "15",
    //             redirectUrl: "/diploma/banking-finance",
    //             specialization: null
    //           },
    //           {
    //             value: "2",
    //             name: "Business",
    //             extraEdgeSpecializationId: "157",
    //             mlid: "41505",
    //             clid: "15",
    //             redirectUrl: "/diploma/business",
    //              specialization: null
    //           },
    //           {
    //               value: "3",
    //               name: "Cyber Security",
    //               extraEdgeSpecializationId: "156",
    //               mlid: "41504",
    //               clid: "15",
    //               redirectUrl: "/diploma/cyber-security",
    //                specialization: null
    //             },
    //             {
    //               value: "4",
    //               name: "Internet Of Things",
    //               extraEdgeSpecializationId: "155",
    //               mlid: "41503",
    //               clid: "15",
    //               redirectUrl: "/diploma/internet-of-things",
    //                specialization: null
    //             },
    //             {
    //               value: "5",
    //               name: "Web And Application",
    //               extraEdgeSpecializationId: "154",
    //               mlid: "41502",
    //               clid: "15",
    //               redirectUrl: "/diploma/web-and-application",
    //                specialization: null
    //             },
    //             {
    //               value: "6",
    //               name: "AI and Machine Learning",
    //               extraEdgeSpecializationId: "158",
    //               mlid: "41506",
    //               clid: "15",
    //               redirectUrl: "/diploma/ai-machine-learning",
    //                specialization: null
    //             },
    //             {
    //               value: "7",
    //               name: "Marketing",
    //               extraEdgeSpecializationId: "159",
    //               mlid: "41507",
    //               clid: "15",
    //               redirectUrl: "/diploma/course-marketing",
    //                specialization: null
    //             },
    //             {
    //               value: "8",
    //               name: "HR Management",
    //               extraEdgeSpecializationId: "153",
    //               mlid: "41501",
    //               clid: "15",
    //               redirectUrl: "/diploma/hr-management",
    //                specialization: null
    //             },
  
    //         ],
        
    // },
  
    // //Certificate
    // {
    //   value: "3",
    //   name: "Certificate",
    //   elid: "5",
    //   clid: "16",
    //   extraEdgeCourseId: "18",
    //   subCourses: [
    //           {
    //             value: "1",
    //             name: "Project Management",
    //             extraEdgeSpecializationId: "170",
    //             mlid: "51604",
    //             redirectUrl: "/certificates/project-management",
    //             clid: "16",
    //              specialization: null
    //           },
    //           {
    //             value: "2",
    //             name: "Business Management",
    //             extraEdgeSpecializationId: "168",
    //             mlid: "51602",
    //             clid: "16",
    //             redirectUrl: "/certificates/business-management",
    //              specialization: null
    //           },
    //           {
    //               value: "3",
    //               name: "Corporate Communications",
    //               extraEdgeSpecializationId: "173",
    //               mlid: "51607",
    //               clid: "16",
    //               redirectUrl: "/certificates/corporate-communications",
    //                specialization: null
    //             },
    //             {
    //               value: "4",
    //               name: "Data Science",
    //               extraEdgeSpecializationId: "166",
    //               mlid: "51600",
    //               clid: "16",
    //               redirectUrl: "/certificates/data-science",
    //                specialization: null
    //             },
    //             {
    //               value: "5",
    //               name: "Digital Marketing",
    //               extraEdgeSpecializationId: "167",
    //               mlid: "51601",
    //               clid: "16",
    //               redirectUrl: "/certificates/digital-marketing",
    //                specialization: null
    //             },
    //             {
    //               value: "6",
    //               name: "Hospital Healthcare",
    //               extraEdgeSpecializationId: "174",
    //               mlid: "51608",
    //               clid: "16",
    //               redirectUrl: "/certificates/hospital-healthcare",
    //                specialization: null
    //             },
    //             {
    //               value: "7",
    //               name: "IT Management",
    //               extraEdgeSpecializationId: "169",
    //               mlid: "51603",
    //               clid: "16",
    //               redirectUrl: "/certificates/it-management",
    //                specialization: null
    //             },
    //             {
    //               value: "8",
    //               name: "Operations Management",
    //               extraEdgeSpecializationId: "171",
    //               mlid: "51605",
    //               clid: "16",
    //               redirectUrl: "/certificates/operations-management",
    //                specialization: null
    //             },
    //             {
    //               value: "9",
    //               clid: "16",
    //               name: "Social Media, Content Marketing & Digital Marketing Analytics",
    //               extraEdgeSpecializationId: "172",
    //               mlid: "51606",
  
    //               redirectUrl: "/certificates/social-media",
    //                specialization: null
    //             },
    //             {
    //               value: "10",
    //               name: "Social Media And Content",
    //               extraEdgeSpecializationId: "175",
    //               mlid: "51609",
    //               clid: "16",
    //               redirectUrl: "/certificates/social-media-and-content",
    //               specialization: null
    //             },
    //             {
    //               value: "11",
    //               name: "Digital Marketing Analytics",
    //               extraEdgeSpecializationId: "177",
    //               mlid: "51611",
    //               clid: "16",
    //               redirectUrl: "/certificates/digital-marketing-analytics",
    //                specialization: null
    //             },
    //             {
    //               value: "12",
    //               name: "Search Engine Marketing",
    //               extraEdgeSpecializationId: "180",
    //               mlid: "51614",
    //               clid: "16",
    //               redirectUrl: "/certificates/search-engine-marketing",
    //                specialization: null
    //             },
    //             {
    //               value: "13",
    //               name: "Search Engine Digital Marketing",
    //               extraEdgeSpecializationId: "178",
    //               mlid: "51612",
    //               clid: "16",
    //               redirectUrl: "/certificates/marketing_analytic",
    //                specialization: null
    //             },
    //             {
    //               value: "14",
    //               name: "SEM & Social Media & Content Marketing",
    //               extraEdgeSpecializationId: "179",
    //               mlid: "51613",
    //               clid: "16",
    //               redirectUrl: "/certificates/sem-content-marketing",
    //                specialization: null
    //             },
    //         ],
    // }
  ];
  